spring:
  datasource:
    username: admin
    password: asd
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/Users/DoctorOne/Desktop/MKCustom/run/h2db
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create