spring:
  datasource:
    username: admin
    password: Secret_Pass
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/h2db
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect